Neos:
  Neos:
    Ui:
      resources:
        javascript:
          '@sitegeist/inspectorgadget-plugin':
            resource: 'resource://Sitegeist.InspectorGadget/Public/JavaScript/Plugin.js'
        stylesheets:
          '@sitegeist/inspectorgadget-plugin':
            resource: 'resource://Sitegeist.InspectorGadget/Public/Css/Plugin.css'